### ISSUE TITLE
Implement source selection

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#53] opened 2017-11-21 13:28 UTC
• Add source selection to settings panel
• Modify code to use this setting

**Comment by jeffwallman** [comment] 2017-12-16 12:49
The default source is China.  I believe we discussed this.  But already Karma and I tested and found that we couldn't download PDFs.  This was because the default source was marked as China.  Either the Library Source needs to be displayed on the home screen at start up?  Or we need some indication to the user that this setting exists.

**Comment by subsystem7** [comment] 2017-12-16 14:49
Yeah, I think you are right, Jeff. This type of setting is really hard for users to understand. Especially since we are making assumptions at setup based on the language they choose. 

## Option 1:

The ideal solution is that we have two apps: BDRC Lib China Edition and BDRC Lib Standard Edition. We could call them CE and SE. These apps would be EXACTLY the same, except that one would be preloaded to point to the servers in China. The settings would allow you to switch source. 


## Option 2: 

As part of initial setup, you select source. Just like selecting language. We can make it clear that you can change this at any time in settings, but that you should select China if you are using the app within China, etc etc.  


## Option 3:

We find some way to display which source is being used. This would be a tricky bit of interface work (and some messaging using existing message locations), but perhaps worth it, and perhaps worth it even if we choose option 1 and/or option 2. 


## Another consideration:

We could have a status light that shows online/offline library source. This is tricky to do effectively, or rather, accurately, but I am sure we could do something. 

What do you think? Would you like me to get more specific on some of these options? Should we setup a meeting?

**Comment by xristy** [comment] 2017-12-16 15:13
There was a missing eBooks dir on the cn server that might have gotten in the way of generating pdfs via the app.

**Comment by jeffwallman** [comment] 2017-12-16 15:15
I think Option 2 is the best option. Can we move forward with that?

**Comment by subsystem7** [comment] 2017-12-16 15:23
We sure can. Do you want to consider any changes in messaging throughout the app? 

### Sequence: 

• Select Language
• Select Server (default selected is based on language selection)
• Run the DB index imports 

### Select server Panel (in the selected Language)

Library Source **sourceSelectTitle**

Please select a server for library source. Please note that this can be changed at any time within the settings panel. If you are in China, the USA server will not work. If you are not within China, it is possible that the China servers will not work. **sourceSelectDescription**

(•) China (If you are using the application within China.) **sourceSelectChina**
(  ) USA (If you are using the application from anywhere else in the world.) **sourceSelectUSA**

[SELECT] **sourceSelectButton**

**Comment by ngawangtrinley** [comment] 2017-12-18 05:33
@xristy thanks for the feedback, right now the issue is that the server is down. We'll definitely do more testing when it's back up.

@subsystem7 We should keep going forward with option 2, we already have "Please select library source" would you rather go for a button?

**Comment by subsystem7** [comment] 2017-12-18 09:46
If it is always true, then this would be fine and we can change it in settings, too. However, I do think it might be a good idea to describe why, unless this is likely to cause trouble. Something like "This selection determines the location of the library that you will connect to. If you are in China, only the library in China will work. You can always change this in settings later."  

I have not thought this all the way through, but I can still imagine a lot of confusion. Especially if there are users who are not always in one place or another. I agree that detection would be a better approach - but, this is also fraught with pitfalls. 

Thoughts?

**Comment by jeffwallman** [comment] 2017-12-18 16:20
I think the answer to your question Asa is that what you are proposing is a good idea.  Displaying the sequence in the start up.  I believe that the language NT is proposing is good but I do think there needs to be an explanation..  It's not the library source for our users (what do they care). It's the country they are in that is important (to them).  We will need a localized description as you suggest Asa.  So in the interest of clarity, what Asa is proposing is the solution is the solution and we need some NT to produce the appropriate localizations.

**Comment by subsystem7** [comment] 2017-12-18 19:12
@ngawangtrinley I added the necessary text components to the interface text sheet. Please review the English and add Chinese and Tibetan: 

https://docs.google.com/spreadsheets/d/1MrPjclaT6mLZipgnjRwCD61UKJcFd77MVhS2a_Ffg1Y

Rock over London, rock on, Chicago.

**Closed** 2017-12-20 13:35 UTC
Labels: change request, enhancement, waiting for approval
