### ISSUE TITLE
Problem with search record for items in an outline

### ISSUE THREAD

**Issue by JannTibetan** [BuddhistDigitalResourceCenter/BDRC-Lib-App#89] opened 2021-05-18 18:50 UTC
I searched on Atisha ཨ་ཏི་ཤ་
![IMG_4612](https://user-images.githubusercontent.com/44705185/118706110-fd011600-b7e6-11eb-86af-ac09401afca8.PNG)

The search results included many outline nodes that include the string ཨ་ཏི་ཤ་
![IMG_4614](https://user-images.githubusercontent.com/44705185/118706273-2de14b00-b7e7-11eb-8820-2e51ee180ca6.jpg)

These search results look pretty good to me. I encounter a problem, however, when I click on a search result that is an outline node. Clicking on the title/outline node takes me to a record in which the outline node is the header and then below it is the list of volumes of the given collection but without any indication about which of these volumes contains the sought after text
![IMG_4613](https://user-images.githubusercontent.com/44705185/118706783-c2e44400-b7e7-11eb-8e54-9e987474baf5.PNG)

This is can feel like trying to find a needle in a haystack. Why doesn't the outline show instead, with the desired text highlighted?

**Comment by subsystem7** [comment] 2021-05-18 20:01
@JannTibetan  @eroux I will need help understanding the data specifics. My guess is that this is an index/data issue.

**Comment by eroux** [comment] 2021-05-19 08:21
@subsystem7 this is in the app but it should be easy to fix. What happens (I think) is that the app gets the data about `MW1KG14557_DC50D3` in `workparts/74.json`, which reads

```
{"t": ["རིག་འཛིན་པདྨའི་རྣམ་སྤྲལ་ཨ་ཏི་ཤ"], "id": "MW1KG14557_DC50D3"}
```

that has no subnodes (`"n":[...]`). In that case the app shouldn't display any "Parts", since the node doesn't have subnodes. I think it looks at `"MW1KG14557"` in  `workparts/74.json` which does have all these subparts, but it shouldn't do that

**Comment by subsystem7** [comment] 2021-05-25 14:47
duplicate of #81

**Closed as completed by subsystem7** 2021-05-25 14:47 UTC
Labels: bug, duplicate
