### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#46] opened 2017-07-26 08:13 UTC
Can we take out the "copyright 2017" ? It takes away some of the free and open-source spirit from the whole thing, imo.

![image](https://user-images.githubusercontent.com/17675331/28610885-8b4dd5de-721c-11e7-8532-7234f0064257.png)

**Comment by eroux** [comment] 2017-07-26 08:22
I think what's not clear is the meaning that is conveyed by "copyright 2017": "2017" is a valuable information, although maybe not crucial. "copyright" is less clear, maybe it conveys the meaning of:
- "made by" (in which case "made by" or "provided by" or "an app from" would be a nicer way to state that
- "warning, don't steal our precious app, we do own the copyright", well, I'm not sure why we would say that... if we don't want it to be stolen, we should probably not release it on github with a free license...
- something else?

**Comment by xristy** [comment] 2017-07-26 14:22
Copyright normally attaches automatically once a work is fixed in tangible form and the app is such a form. The explicit acknowledgement that the app is copyright 2017 by BDRC (currently known at www.tbrc.org) does not contradict github availability and free-ness and open-ness. On the other hand if the development of the app was funded by the USAID contract then [it may be considered a work of the United States government](https://www.copyright.gov/title17/92chap1.html#105) and in that case copyright protection may not be available. [See also CC faq](https://creativecommons.org/faq)

**Comment by eroux** [comment] 2017-07-26 14:34
I don't think anyone challenges the assumption that the app is under copyright, I think the point of the issue is to say that it is not useful to highlight it in such a strong way

**Comment by xristy** [comment] 2017-07-26 15:36
I think it may in fact not be under copyright depending how the USAID contract is written and whether it was used to fund the development, of which I am not sure.

Has any user refused to access BDRC content via the app because of the presence of the copyright? Maybe just change to the © character instead of spelling it out?

**Comment by eroux** [comment] 2017-07-26 15:38
I think this is a UI design issue, not a legal or technical issue...

**Comment by xristy** [comment] 2017-07-26 16:02
It is perhaps both. We have a © at the bottom of www.tbrc.org and there's one at the bottom of the github page as well. There is a bit of a legal notice aspect to its appearance on the content presented to the user.

**Closed** 2017-12-20 13:35 UTC
Labels: change request, enhancement
